### ISSUE TITLE
.cfg location

### ISSUE THREAD

**Issue by nigelhorne** [Pricetx/backup#13]
Thank you for the software.  I have one small suggestion.

I don't think it's a good idea to have programs and configuration files in the same place.  I suggest changing

source "${SCRIPTDIR}"/backup.cfg

to

source "${SCRIPTDIR}"/../lib/backup.cfg

Or better still allowing the location of the configuration file to be given as an argument.

**Comment by xCP23x** [comment]
Good suggestion. I'll probably have this done by tonight - I've got it working on my backup.sh, I just need to implement it in deleteoldbackups.sh
